### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by ashishbaghudana** [ashishbaghudana/dtm#3]
- [ ] Installing GSL and GFlags on Hetrad
- [ ] Histogram of speeches per year
- [ ] Reproduce results from [here](http://arxiv.org/pdf/1510.03797.pdf)

**Comment by tmylk** [comment]
Histogram of speeches is not relevant if we are going to follow: 
" In order to allow a dynamic modeling of the
data, we divide the observations by parliamentary sessions, which commence with the initial speech of
the Queen to the House and ranging about 12 calendar months. We obtain a total of 37 sessions, with
an average of about 4800 contributions per session. The number of parliamentary speakers revolves
around 630 at each time unit."

**Comment by tmylk** [comment]
All you need to reproduce is Table 2 from [here](http://arxiv.org/pdf/1510.03797.pdf).
It will not be an exact match but should look similar.
